### ISSUE TITLE
[BUG] The action fails with a `cp: -r not specified; omitting directory

### ISSUE THREAD

**Issue by benblub** [tj-actions/puppeteer#139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

The action fails with a `cp: -r not specified; omitting directory '/home/runner/work/zone/zone/'`

### To Reproduce

workflow yaml
```yaml
      # Puppeteer test
      - name: Checkout
        uses: ./.github/actions/puppeteer

      - name: Test action
        uses: ./
        id: puppeteer-test
        with:
          files: client/src/api/session-pdf-generator.ts # just replace with your test.js

      - name: Copy test output
        uses: tj-actions/docker-cp@v2
        with:
          container: ${{ steps.puppeteer-test.outputs.container-id }}
          source: ${{ steps.puppeteer-test.outputs.home }}/test.pdf
          destination: test.pdf

      - name: Display contents of test.pdf
        run: cat test.pdf
```

The composite action is not in root. Instead it lives in `.github/actions/puppeteer/action.yml`
action.yml
```yaml
name: puppeteer-chrome
description: Run Test through Puppeteer, the headless chrome Node API
author: tj-actions
inputs:
  files:
    description: 'Files to run'
    required: true

outputs:
  container-id:
    description: 'Container ID'
    value: ${{ steps.puppeteer-run.outputs.container-id }}
  home:
    description: 'Home directory'
    value: /home/pptruser

runs:
  using: 'composite'
  steps:
    - name: Run puppeteer
      id: puppeteer-run
      uses: tj-actions/docker-run@v2
      with:
        image: ghcr.io/puppeteer/puppeteer:19.4.1
        name: puppeteer-chrome
        options: '-i --init --cap-add=SYS_ADMIN -v ${{ github.workspace }}:${{ github.workspace }}'
        args: |
          bash -c 'while read -r file; do echo "Running $file..." && mkdir -p $(dirname /home/pptruser/$file) && cp ${{ github.workspace }}/$file /home/pptruser/$file && node $file && echo "Completed executing $file"; done <<< "$(echo "${{ inputs.files }}" | xargs -n1)"'
branding:
  icon: camera-off
  color: white
```

### What OS are you seeing the problem on?

ubuntu-latest or ubuntu-20.04

### Expected behavior?

No error is thrown

### Relevant log output

```shell
Prepare all required actions
Getting action download info
Download action repository 'tj-actions/docker-run@v[2](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:2)' (SHA:957ff81e54cb1f1[3](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:3)3ad1[4](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:4)4523bfa65cd14ae67d6)
Run ./.github/actions/puppeteer
Run tj-actions/docker-run@v2
Run docker run -v "/var/run/docker.sock":"/var/run/docker.sock" --name puppeteer-chrome -i --init --cap-add=SYS_ADMIN -v /home/runner/work/zone/zone:/home/runner/work/zone/zone ghcr.io/puppeteer/puppeteer:1[9](https://github.com/xxx/zone/actions/runs/4182473339/jobs/7245604564#step:12:10).4.1 bash -c 'while read -r file; do echo "Running $file..." && mkdir -p $(dirname /home/pptruser/$file) && cp /home/runner/work/zone/zone/$file /home/pptruser/$file && node $file && echo "Completed executing $file"; done <<< "$(echo "" | xargs -n1)"'
  docker run -v "/var/run/docker.sock":"/var/run/docker.sock" --name puppeteer-chrome -i --init --cap-add=SYS_ADMIN -v /home/runner/work/zone/zone:/home/runner/work/zone/zone ghcr.io/puppeteer/puppeteer:[19](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:21).4.1 bash -c 'while read -r file; do echo "Running $file..." && mkdir -p $(dirname /home/pptruser/$file) && cp /home/runner/work/xxx/xxx/$file /home/pptruser/$file && node $file && echo "Completed executing $file"; done <<< "$(echo "" | xargs -n1)"'
  
  echo "container_id=$(docker ps -a --filter name=puppeteer-chrome -q)" >> "$GITHUB_OUTPUT"
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    CYPRESS_CACHE_FOLDER: /home/runner/.cache/Cypress
    TERM: xterm
Unable to find image 'ghcr.io/puppeteer/puppeteer:19.4.1' locally
19.4.1: Pulling from puppeteer/puppeteer
6[20](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:22)af4e91dbf: Pulling fs layer
fae29f309a72: Pulling fs layer
28fca74d99b6: Pulling fs layer
0b5db87f5b42: Pulling fs layer
fa488706ea13: Pulling fs layer
0380b9b3282f: Pulling fs layer
383dfecd3687: Pulling fs layer
ca59981dc274: Pulling fs layer
4fa5c4b55a85: Pulling fs layer
34f31a800ebb: Pulling fs layer
4f4fb700ef54: Pulling fs layer
ccb84c2817e8: Pulling fs layer
15887df1981a: Pulling fs layer
ca59981dc274: Waiting
4fa5c4b55a85: Waiting
34f31a800ebb: Waiting
4f4fb700ef54: Waiting
ccb84c2817e8: Waiting
15887df1981a: Waiting
0b5db87f5b42: Waiting
fa488706ea13: Waiting
0380b9b3282f: Waiting
383dfecd3687: Waiting
28fca74d99b6: Verifying Checksum
28fca74d99b6: Download complete
fae29f309a72: Verifying Checksum
fae29f309a72: Download complete
620af4e91dbf: Verifying Checksum
620af4e91dbf: Download complete
0380b9b3282f: Verifying Checksum
0380b9b3282f: Download complete
0b5db87f5b42: Verifying Checksum
0b5db87f5b42: Download complete
ca59981dc274: Verifying Checksum
ca59981dc274: Download complete
383dfecd3687: Verifying Checksum
383dfecd3687: Download complete
4fa5c4b55a85: Verifying Checksum
4fa5c4b55a85: Download complete
4f4fb700ef54: Verifying Checksum
4f4fb700ef54: Download complete
ccb84c2817e8: Verifying Checksum
ccb84c2817e8: Download complete
fa488706ea13: Verifying Checksum
fa488706ea13: Download complete
15887df1981a: Verifying Checksum
15887df1981a: Download complete
34f31a800ebb: Verifying Checksum
34f31a800ebb: Download complete
620af4e91dbf: Pull complete
fae29f309a72: Pull complete
28fca74d99b6: Pull complete
0b5db87f5b42: Pull complete
fa488706ea13: Pull complete
0380b9b3282f: Pull complete
383dfecd3687: Pull complete
ca59981dc274: Pull complete
4fa5c4b55a85: Pull complete
34f31a800ebb: Pull complete
4f4fb700ef54: Pull complete
ccb84c2817e8: Pull complete
15887df1981a: Pull complete
Digest: sha[25](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:27)6:ee33fe2bf8756d17c04802f0966bd52a5a201836eef6ac20e9581f[30](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:33)83aff5[32](https://github.com/xxx/xxx/actions/runs/4182473339/jobs/7245604564#step:12:35)
Status: Downloaded newer image for ghcr.io/puppeteer/puppeteer:19.4.1
Running ...
cp: -r not specified; omitting directory '/home/runner/work/xxx/xxx/'
Error: Process completed with exit code 1.
```
```


### Anything else?

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jackton1** [comment]
Hi @benblub i believe the error is due to using the same code in the test.yml file 


```

      - name: Checkout
        uses: ./.github/actions/puppeteer

      - name: Test action
        uses: ./
        id: puppeteer-test
        with:
          files: client/src/api/session-pdf-generator.ts # just replace with your test.js

```

should replaced with 

```

      - name: Checkout
        uses: actions/checkout@v3

      - name: Test action
        uses: tj-actions/puppeteer@v4
        id: puppeteer-test
        with:
          files: client/src/api/session-pdf-generator.ts

```

> Also note that except your test is generating a test.pdf file there’s no need to have that code.
